name: CI

on:
  push:
  pull_request:
      branches: [master]

jobs:
  test:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Install xcodes
        run: brew install robotsandpencils/made/xcodes

      - name: Download Xcode
        run: xcodes download --directory "$PWD" 14.0.1

      - name: Build unxip
        run: swift build --configuration release

      - name: Run unxip
        run: .build/release/unxip Xcode-14.0.1+14A400.xip

      - name: Validate Xcode
        run: diff -r Xcode.app /Applications/Xcode_14.0.1.app > diff && cat diff && ! test -s diff
